In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('../input/kddcup.data_10_percent_corrected')
#data

In [3]:
categorical_index = [1,2,3,6,11,20,21]
unique_list = []

unique1 = data.iloc[:,1].unique()
unique_list.append(unique1)
unique2 = data.iloc[:,2].unique()
unique_list.append(unique2)
unique3 = data.iloc[:,3].unique()
unique_list.append(unique3)
unique4 = data.iloc[:,6].unique()
unique_list.append(unique4)
unique5 = data.iloc[:,11].unique()
unique_list.append(unique5)
unique6 = data.iloc[:,20].unique()
unique_list.append(unique6)
unique7 = data.iloc[:,21].unique()
unique_list.append(unique7)
#print(unique_list)
#print(len(unique_list))
#print(unique2)

In [4]:
value = 0
for i in range(len(unique1)):
    data.iloc[:,1] = np.where(data.iloc[:,1]==unique1[i], value, data.iloc[:,1])
    value = value + 1

value = 0
for i in range(len(unique2)):
    data.iloc[:,2] = np.where(data.iloc[:,2]==unique2[i], value, data.iloc[:,2])
    value = value + 1

value = 0
for i in range(len(unique3)):
    data.iloc[:,3] = np.where(data.iloc[:,3]==unique3[i], value, data.iloc[:,3])
    value = value + 1

value = 0
for i in range(len(unique4)):
    data.iloc[:,6] = np.where(data.iloc[:,6]==unique4[i], value, data.iloc[:,6])
    value = value + 1

value = 0
for i in range(len(unique5)):
    data.iloc[:,11] = np.where(data.iloc[:,11]==unique5[i], value, data.iloc[:,11])
    value = value + 1

value = 0
for i in range(len(unique6)):
    data.iloc[:,20] = np.where(data.iloc[:,20]==unique6[i], value, data.iloc[:,20])
    value = value + 1

value = 0
for i in range(len(unique7)):
    data.iloc[:,21] = np.where(data.iloc[:,21]==unique7[i], value, data.iloc[:,21])
    value = value + 1
    


In [5]:
label_values = data.iloc[:,41].unique()
print(label_values)
mapping = {}
mapping['smurf.'] = 'DoS'
mapping['neptune.'] = 'DoS'
mapping['back.'] = 'DoS'
mapping['satan.'] = 'probe'
mapping['ipsweep.'] = 'probe'
mapping['portsweep.'] = 'probe'
mapping['warezclient.'] = 'r2l'
mapping['teardrop.'] = 'DoS'
mapping['pod.'] = 'DoS'
mapping['nmap.'] = 'probe'
mapping['guess_passwd.'] = 'r2l'
mapping['buffer_overflow.'] = 'u2r'
mapping['land.'] = 'DoS'
mapping['warezmaster.'] = 'r2l'
mapping['imap.'] = 'r2l'
mapping['rootkit.'] = 'u2r'
mapping['loadmodule.'] = 'u2r'
mapping['ftp_write.'] = 'r2l'
mapping['multihop.'] = 'r2l'
mapping['phf.'] = 'r2l'
mapping['perl.'] = 'u2r'
mapping['spy.'] = 'r2l'
mapping['normal.'] = 'normal'
mapping['normal'] = 'normal'

row_count = data.shape[0]
print(row_count)
label_list = []
for i in range(row_count):
    value = data.iloc[i][41]
    label_list.append(mapping[value])

data.drop(data.columns[41], axis=1, inplace=True)
data.insert(41,41,value = label_list)

#data.replace(to_replace = ['smurf.','neptune.','back.','teardrop.','pod.','land.'],value = 'Dos')
#data.replace(to_replace=['satan.','ipsweep.','portsweep.','nmap.'],value = 'probe')
#data.replace(to_replace=['spy.','phf.','multihop.','ftp_write.','imap,','warezmaster.','guess_passwd.','warezclient.'],value = 'r2l')
#data.replace(to_replace=['loadmodule.','rootkit.','buffer_overflow.','nmap.'],value='u2r')
#data.replace(to_replace=['normal.'],value='normal')


#data.iloc[:,41] = data.iloc[:,41].where(data.iloc[:,41].isin(['smurf.','neptune.','back.','teardrop.','pod.','land.']),'DoS')
#data.iloc[:,41] = data.iloc[:,41].where(data.iloc[:,41].isin(['satan.','ipsweep.','portsweep.','nmap.']),'probe')
#data.iloc[:,41] = data.iloc[:,41].where(data.iloc[:,41].isin(['spy.','phf.','multihop.','ftp_write.','imap,','warezmaster.','guess_passwd.','warezclient.']),'r2l')
#data.iloc[:,41] = data.iloc[:,41].where(data.iloc[:,41].isin(['loadmodule.','rootkit.','buffer_overflow.','nmap.']),'u2r')
#data.iloc[:,41] = data.iloc[:,41].where(data.iloc[:,41].isin(['normal.']),'normal')

print(data.iloc[:,41].unique())


['normal.' 'buffer_overflow.' 'loadmodule.' 'perl.' 'neptune.' 'smurf.'
 'guess_passwd.' 'pod.' 'teardrop.' 'portsweep.' 'ipsweep.' 'land.'
 'ftp_write.' 'back.' 'imap.' 'satan.' 'phf.' 'nmap.' 'multihop.'
 'warezmaster.' 'warezclient.' 'spy.' 'rootkit.']
494020
['normal' 'u2r' 'DoS' 'r2l' 'probe']


In [6]:
# data.iloc[:,41] = np.where(data.iloc[:,41] != 'normal.',1,data.iloc[:,41])
# data.iloc[:,41] = np.where(data.iloc[:,41] == 'normal.',0,data.iloc[:,41])

# data.iloc[:,41].unique()
#print(data)

data.iloc[:,41] = np.where(data.iloc[:,41] == 'normal',0,data.iloc[:,41])
data.iloc[:,41] = np.where(data.iloc[:,41] == 'u2r',1,data.iloc[:,41])
data.iloc[:,41] = np.where(data.iloc[:,41] == 'DoS',2,data.iloc[:,41])
data.iloc[:,41] = np.where(data.iloc[:,41] == 'r2l',3,data.iloc[:,41])
data.iloc[:,41] = np.where(data.iloc[:,41] == 'probe',4,data.iloc[:,41])

print(data.iloc[:,41].unique())

[0 1 2 3 4]


In [7]:
from keras.models import Model
from keras.layers import Input
from keras.utils import np_utils
from keras.layers.core import Dense
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import precision_recall_fscore_support
from sklearn.utils import class_weight

Using TensorFlow backend.


In [8]:
epoch = 100
batchsize = 32

data = data.sample(frac=1,random_state=200)
Input1 = data.iloc[:,:41]
Output1 = data.iloc[:,-1]
Y = np.array(Output1)
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
print(str(encoder.classes_))
Input1 = np.array(Input1)
Y = np_utils.to_categorical(encoded_Y)
print(Input1.shape)
print(Y.shape)
#print(Output1.shape)
print(type(Input1))
print(type(Output1))

[0 1 2 3 4]
(494020, 41)
(494020, 5)
<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>


In [9]:
import math
Input1 = Input1.astype(float)
split = int(math.ceil(0.8 * len(Input1)))
X_train = Input1[0:split]
Y_train = Y[0:split]

X_test = Input1[split:]
Y_test = Y[split:]

print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)
flatten_Y_train = Y_train.ravel()
class_weights = class_weight.compute_class_weight('balanced' ,np.unique(Y_train) ,flatten_Y_train)

(395216, 41)
(98804, 41)
(395216, 5)
(98804, 5)


In [10]:
# Creating the NN Model

inp = Input(shape=(41,))
hidden1 = Dense(40,activation='sigmoid')(inp)
hidden2 = Dense(40,activation='sigmoid')(hidden1)
out = Dense(5,activation='softmax')(hidden2)

model = Model(inp,out)
model.compile(optimizer='adam',loss='categorical_crossentropy')
model.summary()

import time

start = time.time()
model.fit(X_train,Y_train,epochs = epoch,batch_size=batchsize,class_weight=class_weights)
end = time.time()
print("Training Time for Multi-Class NN : ",(end - start))

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 41)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 40)                1680      
_________________________________________________________________
dense_2 (Dense)              (None, 40)                1640      
_________________________________________________________________
dense_3 (Dense)              (None, 5)                 205       
Total params: 3,525
Trainable params: 3,525
Non-trainable params: 0
_________________________________________________________________
Instructions for updating:
Use tf.cast instead.
Epoch 1/100
395216/395216 [==============================] - 16s 40us/step - loss: 0.0418
Epoch 2/100
395216/395216 [==============================] - 1

395216/395216 [==============================] - 16s 39us/step - loss: 0.0139
Epoch 76/100
395216/395216 [==============================] - 15s 38us/step - loss: 0.0174
Epoch 77/100
395216/395216 [==============================] - 15s 38us/step - loss: 0.0107
Epoch 78/100
395216/395216 [==============================] - 15s 38us/step - loss: 0.0115
Epoch 79/100
395216/395216 [==============================] - 15s 38us/step - loss: 0.0108
Epoch 80/100
395216/395216 [==============================] - 15s 38us/step - loss: 0.0107
Epoch 81/100
395216/395216 [==============================] - 15s 38us/step - loss: 0.0136
Epoch 82/100
395216/395216 [==============================] - 15s 38us/step - loss: 0.0148
Epoch 83/100
395216/395216 [==============================] - 15s 38us/step - loss: 0.0177
Epoch 84/100
395216/395216 [==============================] - 15s 38us/step - loss: 0.0106
Epoch 85/100
395216/395216 [==============================] - 15s 38us/step - loss: 0.0087
Epoch 86/100

In [11]:
predicted = model.predict(X_test)
#predicted = predicted.ravel()
print(predicted.shape)
print(predicted)
#print(len(predicted))
Y_predicted = np.empty((len(predicted),))
for i in range(len(predicted)):
    Y_predicted[i] = np.argmax(predicted[i])

print(Y_predicted)
#y_pre,y_pred_counts = np.unique(Y_predicted,return_counts=True)
#print(y_pre,y_pred_counts)

# Y_predicted = Y_predicted.astype(int)


Y_test_final = np.empty((len(Y_test),))
for i in range(len(Y_test)):
    Y_test_final[i] = np.argmax(Y_test[i])
    
    
print(Y_predicted.shape)
print(Y_test_final.shape)
print(type(Y_predicted))
print(type(Y_test_final))

print("Y_predicted Unique and its Frequency :")
y_pre,y_pred_counts = np.unique(Y_predicted,return_counts=True)
print(y_pre,y_pred_counts)

print("Y_test Final unique and its Frequency : ")
y_test_final,y_test_counts = np.unique(Y_test_final,return_counts=True)
print(y_test_final,y_test_counts)

conf = confusion_matrix(Y_test_final,Y_predicted)
print(conf)

precision,recall,f1,support = precision_recall_fscore_support(Y_test_final,Y_predicted)
print("Precision : ",precision)
print("Recall : ",recall)
print("f1 : ",f1)
print("Support : ",support)


# tp,fp,tn,fn = 0,0,0,0
# for i in range(len(Y_test_final)):
#     if Y_test_final[i] == Y_predicted[i] and Y_test_final[i] == 1:
#         tp = tp + 1
#     elif Y_test_final[i] == Y_predicted[i] and Y_test_final[i] == 0:
#         tn = tn + 1
#     elif Y_test_final[i] != Y_predicted[i] and Y_test_final[i] == 0:
#         fp = fp + 1
#     else:
#         fn = fn + 1

# accuracy = (tp+tn)/(tp+tn+fp+fn)
# precision = tp/(tp+fp)
# recall = tp/(tp+fn)
# f1_score = (2*precision*recall)/(precision + recall)
# print("tp :",tp)
# print("tn :",tn)
# print("fp :",fp)
# print("fn :",fn)
# print("Accuracy : ",accuracy)
# print("Precision : ",precision)
# print("Recall : ",recall)
# print("f1_score : ",f1_score)


(98804, 5)
[[9.9978167e-01 1.0976199e-12 5.0180420e-06 2.2507929e-05 1.9079556e-04]
 [1.3123556e-08 1.3064427e-29 1.0000000e+00 9.9648099e-17 7.3719892e-09]
 [7.5469961e-07 6.8072201e-28 9.9999869e-01 5.3274095e-16 6.1854382e-07]
 ...
 [9.9489838e-01 1.8008539e-03 1.2105959e-07 3.0365901e-03 2.6406805e-04]
 [9.9978167e-01 1.0976199e-12 5.0180420e-06 2.2507929e-05 1.9079556e-04]
 [9.9978167e-01 1.0976198e-12 5.0180420e-06 2.2507927e-05 1.9079556e-04]]
[0. 2. 2. ... 0. 0. 0.]
(98804,)
(98804,)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
Y_predicted Unique and its Frequency :
[0. 2. 3. 4.] [19620 78245   113   826]
Y_test Final unique and its Frequency : 
[0. 1. 2. 3. 4.] [19473    12 78253   233   833]
[[19442     0    23     7     1]
 [   12     0     0     0     0]
 [   29     0 78221     0     3]
 [  127     0     1   105     0]
 [   10     0     0     1   822]]
Precision :  [0.99092762 0.         0.99969327 0.92920354 0.99515738]
Recall :  [0.99840805 0.         0.99959107 0.4506

/opt/conda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
