In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('kddcup.data_10_percent_corrected')
#data

In [3]:
categorical_index = [1,2,3,6,11,20,21]
unique_list = []

unique1 = data.iloc[:,1].unique()
unique_list.append(unique1)
unique2 = data.iloc[:,2].unique()
unique_list.append(unique2)
unique3 = data.iloc[:,3].unique()
unique_list.append(unique3)
unique4 = data.iloc[:,6].unique()
unique_list.append(unique4)
unique5 = data.iloc[:,11].unique()
unique_list.append(unique5)
unique6 = data.iloc[:,20].unique()
unique_list.append(unique6)
unique7 = data.iloc[:,21].unique()
unique_list.append(unique7)
#print(unique_list)
#print(len(unique_list))
#print(unique2)

In [4]:
value = 0
for i in range(len(unique1)):
    data.iloc[:,1] = np.where(data.iloc[:,1]==unique1[i], value, data.iloc[:,1])
    value = value + 1

value = 0
for i in range(len(unique2)):
    data.iloc[:,2] = np.where(data.iloc[:,2]==unique2[i], value, data.iloc[:,2])
    value = value + 1

value = 0
for i in range(len(unique3)):
    data.iloc[:,3] = np.where(data.iloc[:,3]==unique3[i], value, data.iloc[:,3])
    value = value + 1

value = 0
for i in range(len(unique4)):
    data.iloc[:,6] = np.where(data.iloc[:,6]==unique4[i], value, data.iloc[:,6])
    value = value + 1

value = 0
for i in range(len(unique5)):
    data.iloc[:,11] = np.where(data.iloc[:,11]==unique5[i], value, data.iloc[:,11])
    value = value + 1

value = 0
for i in range(len(unique6)):
    data.iloc[:,20] = np.where(data.iloc[:,20]==unique6[i], value, data.iloc[:,20])
    value = value + 1

value = 0
for i in range(len(unique7)):
    data.iloc[:,21] = np.where(data.iloc[:,21]==unique7[i], value, data.iloc[:,21])
    value = value + 1
    


In [5]:
label_values = data.iloc[:,41].unique()
print(label_values)
mapping = {}
mapping['smurf.'] = 'DoS'
mapping['neptune.'] = 'DoS'
mapping['back.'] = 'DoS'
mapping['satan.'] = 'probe'
mapping['ipsweep.'] = 'probe'
mapping['portsweep.'] = 'probe'
mapping['warezclient.'] = 'r2l'
mapping['teardrop.'] = 'DoS'
mapping['pod.'] = 'DoS'
mapping['nmap.'] = 'probe'
mapping['guess_passwd.'] = 'r2l'
mapping['buffer_overflow.'] = 'u2r'
mapping['land.'] = 'DoS'
mapping['warezmaster.'] = 'r2l'
mapping['imap.'] = 'r2l'
mapping['rootkit.'] = 'u2r'
mapping['loadmodule.'] = 'u2r'
mapping['ftp_write.'] = 'r2l'
mapping['multihop.'] = 'r2l'
mapping['phf.'] = 'r2l'
mapping['perl.'] = 'u2r'
mapping['spy.'] = 'r2l'
mapping['normal.'] = 'normal'
mapping['normal'] = 'normal'

row_count = data.shape[0]
print(row_count)
label_list = []
for i in range(row_count):
    value = data.iloc[i][41]
    label_list.append(mapping[value])

data.drop(data.columns[41], axis=1, inplace=True)
data.insert(41,41,value = label_list)

#data.replace(to_replace = ['smurf.','neptune.','back.','teardrop.','pod.','land.'],value = 'Dos')
#data.replace(to_replace=['satan.','ipsweep.','portsweep.','nmap.'],value = 'probe')
#data.replace(to_replace=['spy.','phf.','multihop.','ftp_write.','imap,','warezmaster.','guess_passwd.','warezclient.'],value = 'r2l')
#data.replace(to_replace=['loadmodule.','rootkit.','buffer_overflow.','nmap.'],value='u2r')
#data.replace(to_replace=['normal.'],value='normal')


#data.iloc[:,41] = data.iloc[:,41].where(data.iloc[:,41].isin(['smurf.','neptune.','back.','teardrop.','pod.','land.']),'DoS')
#data.iloc[:,41] = data.iloc[:,41].where(data.iloc[:,41].isin(['satan.','ipsweep.','portsweep.','nmap.']),'probe')
#data.iloc[:,41] = data.iloc[:,41].where(data.iloc[:,41].isin(['spy.','phf.','multihop.','ftp_write.','imap,','warezmaster.','guess_passwd.','warezclient.']),'r2l')
#data.iloc[:,41] = data.iloc[:,41].where(data.iloc[:,41].isin(['loadmodule.','rootkit.','buffer_overflow.','nmap.']),'u2r')
#data.iloc[:,41] = data.iloc[:,41].where(data.iloc[:,41].isin(['normal.']),'normal')

print(data.iloc[:,41].unique())


['normal.' 'buffer_overflow.' 'loadmodule.' 'perl.' 'neptune.' 'smurf.'
 'guess_passwd.' 'pod.' 'teardrop.' 'portsweep.' 'ipsweep.' 'land.'
 'ftp_write.' 'back.' 'imap.' 'satan.' 'phf.' 'nmap.' 'multihop.'
 'warezmaster.' 'warezclient.' 'spy.' 'rootkit.']
494020
['normal' 'u2r' 'DoS' 'r2l' 'probe']


In [6]:
# data.iloc[:,41] = np.where(data.iloc[:,41] != 'normal.',1,data.iloc[:,41])
# data.iloc[:,41] = np.where(data.iloc[:,41] == 'normal.',0,data.iloc[:,41])

# data.iloc[:,41].unique()
#print(data)

data.iloc[:,41] = np.where(data.iloc[:,41] == 'normal',0,data.iloc[:,41])
data.iloc[:,41] = np.where(data.iloc[:,41] == 'u2r',1,data.iloc[:,41])
data.iloc[:,41] = np.where(data.iloc[:,41] == 'DoS',2,data.iloc[:,41])
data.iloc[:,41] = np.where(data.iloc[:,41] == 'r2l',3,data.iloc[:,41])
data.iloc[:,41] = np.where(data.iloc[:,41] == 'probe',4,data.iloc[:,41])

print(data.iloc[:,41].unique())

[0 1 2 3 4]


In [7]:
from keras.models import Model
from keras.layers import Input
from keras.utils import np_utils
from keras.layers.core import Dense
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import precision_recall_fscore_support
from sklearn.utils import class_weight
import itertools
import copy
from sklearn.decomposition import PCA

/home/rajat/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [8]:
epoch = 100
batchsize = 32

data = data.sample(frac=1,random_state=200)
Input1 = data.iloc[:,:41]
Output1 = data.iloc[:,-1]

In [9]:
col_to_remove = [i for i in Input1.columns if len(Input1.loc[:,i].unique()) == 1]
a = Input1.drop(col_to_remove, axis = 1)
size = len(a.columns)
Similiarity = np.zeros((size,size))
for col1,col2 in itertools.product(range(size), range(size)):
    pca  = PCA(n_components = 2)
    pca.fit(a.iloc[:,[col1,col2]])
    Similiarity[col1][col2] = np.amin(pca.explained_variance_)


k = 8
features_to_select = np.full(size, True)

while k != 1:
    t_Similiarity = copy.deepcopy(Similiarity[features_to_select])
    index = np.argpartition(t_Similiarity, k)

    min_index     = np.argmin(t_Similiarity[range(len(t_Similiarity)),index[:,k]])
    epsilon       = t_Similiarity[min_index, k]
    
    features_to_select[index[min_index,:k]] = False
    features_to_select[min_index] = True
    
    if((k + 1) > np.sum(features_to_select)):
        k = np.sum(features_to_select) - 1
        if k == 1:
            break
    
    next_epsilon = float('inf')
    while(epsilon < next_epsilon):
        k = k - 1
        if k == 1:
            break
        t_Similiarity  = Similiarity[features_to_select]
        index          = np.argpartition(t_Similiarity, k)
        min_index      = np.argmin(t_Similiarity[range(len(t_Similiarity)),index[:,k]])
        next_epsilon   = t_Similiarity[min_index, k]

np.sum(features_to_select)
Input1 = Input1.iloc[:,features_to_select]

In [10]:
Y = np.array(Output1)
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
print(str(encoder.classes_))
Input1 = np.array(Input1)
Y = np_utils.to_categorical(encoded_Y)
print(Input1.shape)
print(Y.shape)
#print(Output1.shape)
print(type(Input1))
print(type(Output1))

[0 1 2 3 4]
(494020, 31)
(494020, 5)
<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>


In [11]:
import math
Input1 = Input1.astype(float)
split = int(math.ceil(0.8 * len(Input1)))
X_train = Input1[0:split]
Y_train = Y[0:split]

X_test = Input1[split:]
Y_test = Y[split:]

print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)
flatten_Y_train = Y_train.ravel()
class_weights = class_weight.compute_class_weight('balanced' ,np.unique(Y_train) ,flatten_Y_train)

(395216, 31)
(98804, 31)
(395216, 5)
(98804, 5)


In [12]:
# Creating the NN Model

inp = Input(shape=(31,))
hidden1 = Dense(40,activation='sigmoid')(inp)
hidden2 = Dense(40,activation='sigmoid')(hidden1)
out = Dense(5,activation='softmax')(hidden2)

model = Model(inp,out)
model.compile(optimizer='adam',loss='categorical_crossentropy')
model.summary()

import time

start = time.time()
model.fit(X_train,Y_train,epochs = epoch,batch_size=batchsize,class_weight=class_weights)
end = time.time()
print("Training Time for Multi-Class NN : ",(end - start))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 31)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 40)                1280      
_________________________________________________________________
dense_2 (Dense)              (None, 40)                1640      
_________________________________________________________________
dense_3 (Dense)              (None, 5)                 205       
Total params: 3,125
Trainable params: 3,125
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
395216/395216 [==============================] - 41s 103us/step - loss: 0.0434
Epoch 2/100
395216/395216 [==============================] - 25s 63us/step - loss: 0.0284
Epoch 3/100
395216/395216 [==============================] - 23s 58us/step - loss: 0.0245
E

In [13]:
predicted = model.predict(X_test)
#predicted = predicted.ravel()
print(predicted.shape)
print(predicted)
#print(len(predicted))
Y_predicted = np.empty((len(predicted),))
for i in range(len(predicted)):
    Y_predicted[i] = np.argmax(predicted[i])

print(Y_predicted)
#y_pre,y_pred_counts = np.unique(Y_predicted,return_counts=True)
#print(y_pre,y_pred_counts)

# Y_predicted = Y_predicted.astype(int)


Y_test_final = np.empty((len(Y_test),))
for i in range(len(Y_test)):
    Y_test_final[i] = np.argmax(Y_test[i])
    
    
print(Y_predicted.shape)
print(Y_test_final.shape)
print(type(Y_predicted))
print(type(Y_test_final))

print("Y_predicted Unique and its Frequency :")
y_pre,y_pred_counts = np.unique(Y_predicted,return_counts=True)
print(y_pre,y_pred_counts)

print("Y_test Final unique and its Frequency : ")
y_test_final,y_test_counts = np.unique(Y_test_final,return_counts=True)
print(y_test_final,y_test_counts)

conf = confusion_matrix(Y_test_final,Y_predicted)
print(conf)

precision,recall,f1,support = precision_recall_fscore_support(Y_test_final,Y_predicted)
print("Precision : ",precision)
print("Recall : ",recall)
print("f1 : ",f1)
print("Support : ",support)


# tp,fp,tn,fn = 0,0,0,0
# for i in range(len(Y_test_final)):
#     if Y_test_final[i] == Y_predicted[i] and Y_test_final[i] == 1:
#         tp = tp + 1
#     elif Y_test_final[i] == Y_predicted[i] and Y_test_final[i] == 0:
#         tn = tn + 1
#     elif Y_test_final[i] != Y_predicted[i] and Y_test_final[i] == 0:
#         fp = fp + 1
#     else:
#         fn = fn + 1

# accuracy = (tp+tn)/(tp+tn+fp+fn)
# precision = tp/(tp+fp)
# recall = tp/(tp+fn)
# f1_score = (2*precision*recall)/(precision + recall)
# print("tp :",tp)
# print("tn :",tn)
# print("fp :",fp)
# print("fn :",fn)
# print("Accuracy : ",accuracy)
# print("Precision : ",precision)
# print("Recall : ",recall)
# print("f1_score : ",f1_score)


(98804, 5)
[[9.6789181e-01 2.3124768e-12 3.0449897e-02 1.6582143e-03 3.6687744e-08]
 [1.0427010e-06 0.0000000e+00 9.9999893e-01 4.8911558e-10 2.6390121e-11]
 [1.3196403e-07 0.0000000e+00 9.9999988e-01 3.7867860e-12 2.6025282e-12]
 ...
 [9.6789181e-01 2.3124946e-12 3.0449897e-02 1.6582143e-03 3.6687879e-08]
 [9.6789181e-01 2.3124857e-12 3.0449897e-02 1.6582143e-03 3.6687879e-08]
 [9.6789181e-01 2.3124725e-12 3.0449955e-02 1.6582174e-03 3.6687812e-08]]
[0. 2. 2. ... 0. 0. 0.]
(98804,)
(98804,)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
Y_predicted Unique and its Frequency :
[0. 1. 2. 3. 4.] [19975     9 77825   198   797]
Y_test Final unique and its Frequency : 
[0. 1. 2. 3. 4.] [19473    12 78253   233   833]
[[19445     4    16     8     0]
 [    7     2     0     1     2]
 [  446     0 77806     1     0]
 [   39     3     3   188     0]
 [   38     0     0     0   795]]
Precision :  [0.97346683 0.22222222 0.99975586 0.94949495 0.99749059]
Recall :  [0.99856211 0.16666667 0.994287