In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('../input/kddcup.data_10_percent_corrected')
#data

In [3]:
categorical_index = [1,2,3,6,11,20,21]
unique_list = []

unique1 = data.iloc[:,1].unique()
unique_list.append(unique1)
unique2 = data.iloc[:,2].unique()
unique_list.append(unique2)
unique3 = data.iloc[:,3].unique()
unique_list.append(unique3)
unique4 = data.iloc[:,6].unique()
unique_list.append(unique4)
unique5 = data.iloc[:,11].unique()
unique_list.append(unique5)
unique6 = data.iloc[:,20].unique()
unique_list.append(unique6)
unique7 = data.iloc[:,21].unique()
unique_list.append(unique7)
#print(unique_list)
#print(len(unique_list))
#print(unique2)

In [4]:
value = 0
for i in range(len(unique1)):
    data.iloc[:,1] = np.where(data.iloc[:,1]==unique1[i], value, data.iloc[:,1])
    value = value + 1

value = 0
for i in range(len(unique2)):
    data.iloc[:,2] = np.where(data.iloc[:,2]==unique2[i], value, data.iloc[:,2])
    value = value + 1

value = 0
for i in range(len(unique3)):
    data.iloc[:,3] = np.where(data.iloc[:,3]==unique3[i], value, data.iloc[:,3])
    value = value + 1

value = 0
for i in range(len(unique4)):
    data.iloc[:,6] = np.where(data.iloc[:,6]==unique4[i], value, data.iloc[:,6])
    value = value + 1

value = 0
for i in range(len(unique5)):
    data.iloc[:,11] = np.where(data.iloc[:,11]==unique5[i], value, data.iloc[:,11])
    value = value + 1

value = 0
for i in range(len(unique6)):
    data.iloc[:,20] = np.where(data.iloc[:,20]==unique6[i], value, data.iloc[:,20])
    value = value + 1

value = 0
for i in range(len(unique7)):
    data.iloc[:,21] = np.where(data.iloc[:,21]==unique7[i], value, data.iloc[:,21])
    value = value + 1
    

In [5]:
label_values = data.iloc[:,41].unique()
print(label_values)
mapping = {}
mapping['smurf.'] = 'DoS'
mapping['neptune.'] = 'DoS'
mapping['back.'] = 'DoS'
mapping['satan.'] = 'probe'
mapping['ipsweep.'] = 'probe'
mapping['portsweep.'] = 'probe'
mapping['warezclient.'] = 'r2l'
mapping['teardrop.'] = 'DoS'
mapping['pod.'] = 'DoS'
mapping['nmap.'] = 'probe'
mapping['guess_passwd.'] = 'r2l'
mapping['buffer_overflow.'] = 'u2r'
mapping['land.'] = 'DoS'
mapping['warezmaster.'] = 'r2l'
mapping['imap.'] = 'r2l'
mapping['rootkit.'] = 'u2r'
mapping['loadmodule.'] = 'u2r'
mapping['ftp_write.'] = 'r2l'
mapping['multihop.'] = 'r2l'
mapping['phf.'] = 'r2l'
mapping['perl.'] = 'u2r'
mapping['spy.'] = 'r2l'
mapping['normal.'] = 'normal'
mapping['normal'] = 'normal'

row_count = data.shape[0]
print(row_count)
label_list = []
for i in range(row_count):
    value = data.iloc[i][41]
    label_list.append(mapping[value])

data.drop(data.columns[41], axis=1, inplace=True)
data.insert(41,41,value = label_list)

#data.replace(to_replace = ['smurf.','neptune.','back.','teardrop.','pod.','land.'],value = 'Dos')
#data.replace(to_replace=['satan.','ipsweep.','portsweep.','nmap.'],value = 'probe')
#data.replace(to_replace=['spy.','phf.','multihop.','ftp_write.','imap,','warezmaster.','guess_passwd.','warezclient.'],value = 'r2l')
#data.replace(to_replace=['loadmodule.','rootkit.','buffer_overflow.','nmap.'],value='u2r')
#data.replace(to_replace=['normal.'],value='normal')


#data.iloc[:,41] = data.iloc[:,41].where(data.iloc[:,41].isin(['smurf.','neptune.','back.','teardrop.','pod.','land.']),'DoS')
#data.iloc[:,41] = data.iloc[:,41].where(data.iloc[:,41].isin(['satan.','ipsweep.','portsweep.','nmap.']),'probe')
#data.iloc[:,41] = data.iloc[:,41].where(data.iloc[:,41].isin(['spy.','phf.','multihop.','ftp_write.','imap,','warezmaster.','guess_passwd.','warezclient.']),'r2l')
#data.iloc[:,41] = data.iloc[:,41].where(data.iloc[:,41].isin(['loadmodule.','rootkit.','buffer_overflow.','nmap.']),'u2r')
#data.iloc[:,41] = data.iloc[:,41].where(data.iloc[:,41].isin(['normal.']),'normal')

print(data.iloc[:,41].unique())

['normal.' 'buffer_overflow.' 'loadmodule.' 'perl.' 'neptune.' 'smurf.'
 'guess_passwd.' 'pod.' 'teardrop.' 'portsweep.' 'ipsweep.' 'land.'
 'ftp_write.' 'back.' 'imap.' 'satan.' 'phf.' 'nmap.' 'multihop.'
 'warezmaster.' 'warezclient.' 'spy.' 'rootkit.']
494020
['normal' 'u2r' 'DoS' 'r2l' 'probe']


In [6]:
# data.iloc[:,41] = np.where(data.iloc[:,41] != 'normal.',1,data.iloc[:,41])
# data.iloc[:,41] = np.where(data.iloc[:,41] == 'normal.',0,data.iloc[:,41])

# data.iloc[:,41].unique()
#print(data)

data.iloc[:,41] = np.where(data.iloc[:,41] == 'normal',0,data.iloc[:,41])
data.iloc[:,41] = np.where(data.iloc[:,41] == 'u2r',1,data.iloc[:,41])
data.iloc[:,41] = np.where(data.iloc[:,41] == 'DoS',2,data.iloc[:,41])
data.iloc[:,41] = np.where(data.iloc[:,41] == 'r2l',3,data.iloc[:,41])
data.iloc[:,41] = np.where(data.iloc[:,41] == 'probe',4,data.iloc[:,41])

print(data.iloc[:,41].unique())

[0 1 2 3 4]


In [7]:
# Separating Data and the Output labels into data and Y respectively

print(data.shape)
Y = data.iloc[:,41]
Y = np.array(Y)
#Y = Y.reshape(Y.shape[0],1)
print(Y.shape)
data.drop(data.columns[41], axis=1, inplace=True)
print(data.shape)

(494020, 42)
(494020,)
(494020, 41)


In [8]:
# Splitting Data into train and test
from sklearn.model_selection import train_test_split  
X_train, X_test, Y_train, Y_test = train_test_split(data, Y, test_size = 0.20) 

X_train = np.array(X_train)
X_test = np.array(X_test)
Y_train = np.array(Y_train)
#Y_train = Y_train.reshape(Y_train.shape[0],1)
Y_test = np.array(Y_test)
#Y_test = Y_test.reshape(Y_test.shape[0],1)

print("X_train : ",X_train.shape)
print("X_test : ",X_test.shape)
print("Y_train : ",Y_train.shape)
print("Y_test : ",Y_test.shape)

X_train :  (395216, 41)
X_test :  (98804, 41)
Y_train :  (395216,)
Y_test :  (98804,)


In [9]:
# Preprocessing in order to do the computation faster doing scaling can use MinMaxScaler as well...
# Check how SVM learns in terms of distance calculation


from sklearn import svm
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder


X_train = X_train.astype(float)
scaler = preprocessing.StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
print("X_train Shape : ", X_train.shape)

Y_train = np.array(Y_train)
encoder = LabelEncoder()
encoder.fit(Y_train)
Y_train = encoder.transform(Y_train)
print("Y_train Shape : ",Y_train.shape)

X_test = X_test.astype(float)
scaler = preprocessing.StandardScaler()
scaler.fit(X_test)
X_test = scaler.transform(X_test)
print("X_train Shape : ", X_train.shape)

Y_test = encoder.transform(Y_test)
print("Y_test Shape : ",Y_test.shape)

X_train Shape :  (395216, 41)
Y_train Shape :  (395216,)
X_train Shape :  (395216, 41)
Y_test Shape :  (98804,)


In [10]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.utils import class_weight

#flatten_Y_train = Y_train.ravel()
#class_weights = class_weight.compute_class_weight('balanced' ,np.unique(Y_train) ,flatten_Y_train)
grid_param = {
    'kernel': ['rbf','linear'],
    'C' : [1,10,100],
    'gamma':['auto','scale']
}

svm_model = GridSearchCV(SVC(class_weight='balanced'),param_grid=grid_param,cv=5,n_jobs=-1,verbose = 1)
print("Done Setting Up Model..")
svm_model.fit(X_train, Y_train)
print("Done Fitting..")

Done Setting Up Model..
Fitting 5 folds for each of 12 candidates, totalling 60 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed: 80.6min
[Parallel(n_jobs=-1)]: Done  60 out of  60 | elapsed: 250.3min finished


Done Fitting..


In [12]:
print('Best score for training data:', svm_model.best_score_,"\n") 

# View the best parameters for the model found using grid search
print('Best C:',svm_model.best_estimator_.C,"\n") 
print('Best Kernel:',svm_model.best_estimator_.kernel,"\n")
#print('Best Gamma:',svm_model.best_estimator_.gamma,"\n")

Best score for training data: 0.9991068175377515 

Best C: 100 

Best Kernel: rbf 



In [13]:
from sklearn.metrics import confusion_matrix,classification_report
final_model = svm_model.best_estimator_
Y_pred = final_model.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print("\n")
print(classification_report(Y_test,Y_pred))

[[19419     3     2    70    17]
 [   15     2     0     0     1]
 [  383     0 77886     0     0]
 [   30     0     0   182     0]
 [    6     0     0     0   788]]


              precision    recall  f1-score   support

           0       0.98      1.00      0.99     19511
           1       0.40      0.11      0.17        18
           2       1.00      1.00      1.00     78269
           3       0.72      0.86      0.78       212
           4       0.98      0.99      0.98       794

   micro avg       0.99      0.99      0.99     98804
   macro avg       0.82      0.79      0.79     98804
weighted avg       0.99      0.99      0.99     98804



In [ ]:
# from sklearn.metrics import confusion_matrix
# from sklearn.metrics import precision_recall_fscore_support
# predicted = predicted.astype(int)
# conf = confusion_matrix(Y_test,predicted)
# print(conf)

# precision,recall,f1,support = precision_recall_fscore_support(Y_test,predicted)
# print("Precision : ",precision)
# print("Recall : ",recall)
# print("f1 : ",f1)
# print("Support : ",support)

In [14]:
pred = Y_pred.tolist()
print("0 occurence in Predicted List : ",pred.count(0))
print("1 occurence in Predicted List : ",pred.count(1))
print("2 occurence in Predicted List : ",pred.count(2))
print("3 occurence in Predicted List : ",pred.count(3))
print("4 occurence in Predicted List : ",pred.count(4))

0 occurence in Predicted List :  19853
1 occurence in Predicted List :  5
2 occurence in Predicted List :  77888
3 occurence in Predicted List :  252
4 occurence in Predicted List :  806


In [15]:
actual = Y_test.tolist()
print("0 occurence in Actual List : ",actual.count(0))
print("1 occurence in Actual List : ",actual.count(1))
print("2 occurence in Actual List : ",actual.count(2))
print("3 occurence in Actual List : ",actual.count(3))
print("4 occurence in Actual List : ",actual.count(4))

0 occurence in Actual List :  19511
1 occurence in Actual List :  18
2 occurence in Actual List :  78269
3 occurence in Actual List :  212
4 occurence in Actual List :  794
